export const  GET_MEDICALFILES="GET_MEDICALFILES";
export const POST_MEDICALFILES="POST_MEDICALFILES";
export const AUTH_ERRORS="POST_MEDICALFILES";
export const USER_LOADING="POST_MEDICALFILES";
export const GET_AUTH_USER="GET_AUTH_USER";